### ISSUE TITLE
What's the reason of this error？

### ISSUE THREAD

**Issue by RiotGamesPlayer** [ammarsys/riot-password-changer#1]
![image](https://user-images.githubusercontent.com/126843138/224463686-6d5ef598-3067-4ea0-9ade-ed217dadd9cb.png)

**Comment by RiotGamesPlayer** [comment]
![image](https://user-images.githubusercontent.com/126843138/224469622-41360f68-c9f1-4f2c-82e1-06e3efd5f6ae.png)

**Comment by ammarsys** [comment]
Hi, are you just running the script via the `POKRENI_ME.bat`? Can you provide the error in text format?

**Comment by RiotGamesPlayer** [comment]
I have solve the problems.because the chrome didn't work，so i re-downloaded the right vision of Chromedrive matched the vision of chrome exe，and after Reset computer，that's solved.

**Comment by RiotGamesPlayer** [comment]
If it can be changed to the password I specified, I think it might be better.it will be changed to a random password now.

**Comment by ammarsys** [comment]
Awesome! Glad to hear it is working. It does seem to be an issue with Chrome version even on my machine, so I went ahead and updated `requirements.txt` to not download a specific version (i.e. download the latest one) and specified `version_main=109` in Driver Initialization as per [issue on undetected_chromedriver 1047.](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1047)

As for the feature idea, you're welcome to open a PR that implements it :) I think that the best way to go about this is to edit the format in `accounts.txt` to allow a *second* `:` which would indicate the desired user password. This would then be parsed in `main.py` and the Line 44 could be edited to look like:

`new_password = desired_password or gen_sec_pass()`

This would allow for desired_password to fall back to randomly generated password if the user did not provide it i.e. the variable is none.

**Comment by RiotGamesPlayer** [comment]
To be honest，i am a fresh，so i don't know how to make it.but i will have a try.

**Comment by ammarsys** [comment]
Awesome! Let me know if you decide to do it.

**Comment by ammarsys** [comment]
I will close this issue and open up a new one specifically for the feature request.
