### ISSUE TITLE
hello i am getting error

### ISSUE THREAD

**Issue by cinarss07** [ammarsys/riot-password-changer#4]
I am getting an error like
![image](https://github.com/ammarsys/riot-password-changer/assets/127631501/c4b30769-5e38-4693-9973-38de7330aea5)

**Comment by ammarsys** [comment]
Hi!

I will update the repository soon to fix this.

**Comment by cinarss07** [comment]
thanks but can you post it here when it is updated

**Comment by ammarsys** [comment]
Yes, of course!

Have a lovely evening.

**Comment by cinarss07** [comment]
I'm from Turkey here at night 

Good night

**Comment by ammarsys** [comment]
Okay, I've gone ahead and pushed an update. I was not able to replicate the error but I made it so that it automatically detects the chrome version.

Can you do the following:

1. Update your Google Chrome version
2. Update the codebase
3. Run `RUN_ME.bat`

Also, I've translated the instructions to English and added a new feature. Please let me know if it works!

**Comment by cinarss07** [comment]
How will the account.txt account order be? for example how to string username and password

**Comment by ammarsys** [comment]
Each account must be in a new line. The format is,

name:password

and optionally,

name:password:newpassword

The program goes through them one by one.

**Comment by cinarss07** [comment]
I will only make one account

**Comment by ammarsys** [comment]
That's okay. Does the program work now?

**Comment by cinarss07** [comment]
i get the same error i updated chrome

**Comment by ammarsys** [comment]
Could you follow the steps in [this issue](https://github.com/ammarsys/riot-password-changer/issues/3#issuecomment-1583435900)?

**Comment by ammarsys** [comment]
Closed due to inactivity. Please look at the comment I left [here](https://github.com/ammarsys/riot-password-changer/issues/3#issuecomment-1583435900) on solving your issue.
