### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lejan0** [ammarsys/riot-password-changer#6]
![erroorrrr](https://github.com/ammarsys/riot-password-changer/assets/23408140/7d2879ad-6e58-43d5-9b7f-607cbb91a068)

**Comment by ammarsys** [comment]
Thanks for opening the issue.

Is the issue that the program is not ran at the end of dependency installation?

The `RUN_ME` batch file works fine for me.
![image](https://github.com/ammarsys/riot-password-changer/assets/69536330/4f7de9d8-bb50-42d9-a891-3d576940e8d9)

**Comment by ammarsys** [comment]
Closed due to inactivity, please reopen the thread if issue persists.
