### ISSUE TITLE
Chrome opens to riot page but nothing happens

### ISSUE THREAD

**Issue by Farhda** [ammarsys/riot-password-changer#7]
Hi! I hope that you are doing fine and well. 
I think that your program is supposed to run by opening a google chrome page with lol sign in empty text boxes --> paste the accounts' file Username and password and sign in --> change the password from inside the account; however I'm facing an issue that chrome opens to riot page but nothing happens. Then I get this error code: 

In the file [44maccounts.txt[0m enter all your accounts in the following format,

name:password

for example,

myRiotName:verysecurepassword454!!
ValorantEnjoyer:kkkkk33!!

You can also specify a second ":" which indicates your desired password. This means that the program will not generate
a random password but rather, it'll use the one you give it. For example,

myRiotName:verysecurepass:thisismynewpassword!!

A new file [44mnew_accounts.txt[0m will be created & updated as the program goes. Click ENTER to start the program.

Please note that the process is fully autonomous for accounts without a verified email, that is ones that do not require 
2FA entry.

[38;2;128;128;128m[INFO][0m Process started for Tes********
[38;2;128;128;128m[INFO][0m The old password is nq[*****
[38;2;128;128;128m[INFO][0m The new password is [44mr********[0m
Traceback (most recent call last):
  File "C:\Users\xxxxx\Downloads\riot-password-changer-main\riot-password-changer-main\main.py", line 52, in <module>
    change_account_password(username, password, new_password, sleep_time=2)
  File "C:\Users\xxxxxx\Downloads\riot-password-changer-main\riot-password-changer-main\extended\utils.py", line 63, in change_account_password
    WebDriverWait(driver, 40).until(
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	GetHandleVerifier [0x008FA813+48355]
	(No symbol) [0x0088C4B1]
	(No symbol) [0x00795358]
	(No symbol) [0x007C09A5]
	(No symbol) [0x007C0B3B]
	(No symbol) [0x007EE232]
	(No symbol) [0x007DA784]
	(No symbol) [0x007EC922]
	(No symbol) [0x007DA536]
	(No symbol) [0x007B82DC]
	(No symbol) [0x007B93DD]
	GetHandleVerifier [0x00B5AABD+2539405]
	GetHandleVerifier [0x00B9A78F+2800735]
	GetHandleVerifier [0x00B9456C+2775612]
	GetHandleVerifier [0x009851E0+616112]
	(No symbol) [0x00895F8C]
	(No symbol) [0x00892328]
	(No symbol) [0x0089240B]
	(No symbol) [0x00884FF7]
	BaseThreadInitThunk [0x756BFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771D7C5E+286]
	RtlGetAppContainerNamedObjectPath [0x771D7C2E+238]

**Comment by Farhda** [comment]
I am going to try to update Python to a version above 3.9 as I'm using 3.8

Update: I installed python 3.10 and still having the same issue

**Comment by Farhda** [comment]
nvm. Sorry to bother. I sorted the problem by changing the HTML paths. You have my star. <3

**Comment by ammarsys** [comment]
hey -- I'm so sorry for not responding, I was busy with clinicals

if you don't mind, I would appreciate a pull request in case the website structure has changed :)
