### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by Farhda** [ammarsys/riot-password-changer#8]
I hope you are doing great.
Currently you cant sign in unless you solve the captcha manually
Can you implement a captcha solving service like Capmonster cloud ?
Thanks in advance!

**Comment by ammarsys** [comment]
ah, have they added captchas now?

unfourtunately, i do not have access to any (paid) captcha solving services so such implementation remains out of my reach.

**Comment by Farhda** [comment]
That is totally fine, If you're up for it you can hit me and I'll provide you with a Capmonster Cloud API Key.

Appreciate your effort and reply <3
